namespace: "netapp"
name: "aws"
version: "19.11.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "Apache-2.0"
readme: README.md
description: Cloud Volumes Service (CVS) for AWS
repository: https://github.com/ansible/ansible_collections_netapp
homepage: netapp.io
