namespace: "netapp"
name: "aws"
version: "21.6.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license_file: COPYING
readme: README.md
description: Cloud Volumes Service (CVS) for AWS
repository: https://github.com/ansible-collections/netapp.aws
issues: https://github.com/ansible-collections/netapp.aws/issues
homepage: https://netapp.io/configuration-management-and-automation/
tags:
    - storage
    - cloud
    - netapp
    - cvs
    - amazon
    - aws
