namespace: "netapp"
name: "aws"
version: "20.6.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "GPL-2.0-or-later"
readme: README.md
description: Cloud Volumes Service (CVS) for AWS
repository: https://github.com/ansible-collections/netapp
homepage: https://netapp.io/configuration-management-and-automation/
tags:
    - storage
    - cloud
